steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gcp-starter-kit/frontend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcp-starter-kit/frontend:latest']
images:
  - 'gcr.io/gcp-starter-kit/frontend:latest'