apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: imnottheguy/gcp-backend:latest
        name: gcp-backend
        resources: {}
        ports:
        - containerPort: 8080
        env:
        - name: FRONTEND_URL
          value: "http://frontend-service:3000"
status: {}